services:
    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        image: sail-8.3/app
#        extra_hosts:
#            - 'host.docker.internal:host-gateway'
        environment:
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
            - './docker/php/www.conf:/etc/php/8.3/fpm/pool.d/www.conf'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
            - selenium
    nginx:
        image: nginx:alpine
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - '.:/var/www/html'
            - './nginx.conf:/etc/nginx/conf.d/default.conf:ro'
        depends_on:
            - laravel
        networks:
            - sail
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        command:
            - --default-authentication-plugin=mysql_native_password
            - --skip-networking=0
            - --max-connections=1000
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        command: "redis-server --appendonly yes --replica-read-only no"
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    nodejs:
        image: nodejs-apple:latest
        ports:
            - "8088:8088"
        networks:
            - sail
    selenium:
        # image: selenium/standalone-chrome:latest
        image: selenium/hub:latest
        container_name: laravel_selenium
        environment:
            SE_GRID_MAX_SESSION: 100 # 最大会话数
            SE_NODE_MAX_INSTANCES: 100 # 最大会话数
            SE_NODE_MAX_SESSIONS: 100 # 最大会话数
            SE_NODE_OVERRIDE_MAX_SESSIONS: true  # 设置为true来覆盖最大限制
            SE_NODE_OVERRIDE_MAX_INSTANCES: 20 # 最大实例数
            SE_NODE_OVERRIDE_MAX_SESSION: 20 # 最大会话数
            SE_VNC_PASSWORD: '123456' # 调式密码
            SE_SESSION_RETRY_INTERVAL: 1 # 重试间隔
            SE_SESSION_TIMEOUT: 300 # 设置会话超时时间为300秒
            SE_SESSION_REQUEST_TIMEOUT: 600 # 设置会话超时时间为300秒
        ports:
            - '4444:4444'   # Selenium WebDriver 端口
            - '7900:7900'   # VNC 端口（可选，用于访问 Chrome 无头模式）
        shm_size: '8gb'     # 增加共享内存，防止 Chrome 无头模式下崩溃
        networks:
            - sail
    chrome:
        image: selenium/node-chrome:latest
        container_name: laravel_selenium_chrome
        volumes:
            - /dev/shm:/dev/shm
        depends_on:
            - selenium
        environment:
            SE_EVENT_BUS_HOST: selenium
            SE_EVENT_BUS_PUBLISH_PORT: 4442
            SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
            SE_NODE_OVERRIDE_MAX_SESSIONS: true  # 设置为true来覆盖最大限制
            SE_NODE_MAX_SESSION: 20
            SE_NODE_MAX_SESSIONS: 20 #最大会话数
            SE_NODE_MAX_INSTANCES: 20
            SE_VNC_PASSWORD: '123456' # 调式密码
        networks:
            - sail
    firefox:
        image: selenium/node-firefox:latest
        container_name: laravel_selenium_firefox
        volumes:
            - /dev/shm:/dev/shm
        depends_on:
            - selenium
        environment:
            SE_EVENT_BUS_HOST: selenium
            SE_EVENT_BUS_PUBLISH_PORT: 4442
            SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
            SE_NODE_OVERRIDE_MAX_SESSIONS: true  # 设置为true来覆盖最大限制
            SE_NODE_MAX_SESSION: 10
            SE_NODE_MAX_INSTANCES: 10
            SE_NODE_MAX_SESSIONS: 10
            SE_VNC_PASSWORD: '123456' # 调式密码
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
